services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    networks:
      - docker_network
    ports:
      - 32400:32400
    environment:
      - TZ=Europe/Sofia
      - ADVERTISE_IP=http://192.168.88.100:32400/
    volumes:
      - ./plex/config:/config
      - ~/hdds:/hdds
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - docker_network
    volumes:
      - grafana-storage:/var/lib/grafana

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - docker_network
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - docker_network
    restart: unless-stopped

  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100
    networks:
      - docker_network
    restart: unless-stopped

  transmission:
    container_name: transmission
    image: ghcr.io/linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Sofia
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ./transmission/config:/config
      - ./transmission/watch:/watch
      - ~/hdds:/downloads
    networks:
      - docker_network
    restart: unless-stopped

  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - ./frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"

networks:
  docker_network:
    driver: bridge

volumes:
  grafana-storage: {}
