mqtt:
  enabled: false

cameras:
  kindsroom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://testtest:testtest@192.168.107.254:554/stream2
          roles:
            - detect
    detect:
      enabled: false
version: 0.15-1
